Text expansion shortcut
HospitalRun/hospitalrun-frontend pull request #1057
Opened 2017-04-18 19:14 UTC by tangollama

Based entirely on the work of @eddiesholl in 2016, this is the completed feature for review.

**Changes proposed in this pull request:**
- Added model for text-expansion
- Route for CRUD functions of text expansion
- Navigation and locale changes
- Inclusion of the new component in patients, procedures, visits, labs, imaging, incidents, appointments, and inventory

<img width="907" alt="screen shot 2017-04-18 at 3 10 49 pm" src="https://cloud.githubusercontent.com/assets/929261/25148678/a837f2ea-2449-11e7-85c8-1a6ce54d8035.png">

<img width="875" alt="screen shot 2017-04-18 at 3 10 21 pm" src="https://cloud.githubusercontent.com/assets/929261/25148679/a9f939fe-2449-11e7-8bdd-1e4427b3add5.png">

cc @HospitalRun/core-maintainers

2017-04-19 13:17 UTC, jkleinsc requested changes
@tangollama looks good overall, but the translations need to be camelCased instead of using underscores.  Can you also merge in the latest from master?

2017-04-19 13:17 UTC, jkleinsc commented on app/locales/en/translations.js
> +    text_replacements: {
@tangollama these need to be camel cased.

2017-04-19 14:17 UTC, tangollama commented
@jkleinsc bump. Changes checked in.

2017-04-19 14:47 UTC, jkleinsc approved these changes

2017-04-19 14:58 UTC, merged

2022-11-02 19:46 UTC, sthutchinson commented
**I like this.**   _It would really help with notes_._