feat(patient): add panel to display useful patient information
HospitalRun/hospitalrun-frontend pull request #2333
Opened 2020-08-26 14:30 UTC by AlexTan331

fix #2259 

**Changes proposed in this pull request:**

- add panel to display useful patient information

2020-08-27 00:36 UTC, michaelkramer commented
@AlexTan331 I have downloaded and ran your branch.  Would you be open for some critiques?
I can send a more detailed list if you are interested.

1. Mobile view is bad
2. The `add allergies` button is miss placed.
![image](https://user-images.githubusercontent.com/6052223/91370119-809f5080-e7db-11ea-9dbd-3beb0cb24068.png)
3. on file `src/patients/view/ViewPatient.tsx` there is lots of repeat code.  Making an Array and then `map` through would allow for quicker edits in the future.

I have more, but only if you're interested.

2020-08-27 00:53 UTC, AlexTan331 commented
@michaelkramer  Thank you for your critiques. 
This is the my first attempt that successfully made the overall layout in place. It is obviously not ideal, and the reason why I didn't mark it as draft is because I am open to anyone just like you to provide useful suggestion/critiques so that I know if I am on the right path. 
So please share your opinions.

2020-08-27 08:26 UTC, blestab commented on src/__tests__/patients/view/ImportantPatientInfo.test.tsx
> +// import Diagnoses from '../../../patients/diagnoses/Diagnoses'
May we remove the commented out code if it no longer being used

2020-08-27 08:27 UTC, blestab commented on src/__tests__/patients/view/ImportantPatientInfo.test.tsx
> +  //   describe('add new care plan button', () => {
Do we still need this here?

2020-08-27 08:34 UTC, blestab requested changes
Looks like we have a few lines of code commented out. Perhaps we should remove those if there is no plan to use them anymore.

2020-08-27 08:34 UTC, blestab commented on src/patients/view/ImportantPatientInfo.tsx
> +// import  {getPatientFullName} from '../util/patient-name-util'
Remove commented out code

2020-09-23 12:29 UTC, tehKapa commented
@AlexTan331 there are conflicts to resolve

2020-09-28 15:16 UTC, tehKapa requested changes

2020-09-28 15:16 UTC, tehKapa commented on src/patients/view/ViewPatient.tsx
>  import { getPatientCode, getPatientFullName } from '../util/patient-util'
'getPatientCode' is defined but never used

2020-10-08 19:29 UTC, tehKapa approved these changes

2020-10-08 22:18 UTC, morrme commented
LGTM

2020-10-09 09:23 UTC, merged