refactor(page-header):move title functionality to use a TitleProvider
HospitalRun/hospitalrun-frontend pull request #2390
Opened 2020-09-12 01:21 UTC by blestab

Fixes #2354 

**Changes proposed in this pull request:**

- Add a _TitleProvider_ with a _useTitle_ and a _useUpdateTitle_ hooks
- Remove unused redux code

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

NONE

2020-09-12 17:48 UTC, jackcmeyer requested changes
we should also be able to delete
- `title-slice.ts`
- `title-slice.test.ts`

2020-09-12 17:48 UTC, jackcmeyer commented on src/__tests__/labs/Labs.test.tsx
> +      title: 'test',
title is no longer needed in the store

2020-09-12 17:48 UTC, jackcmeyer commented on src/__tests__/HospitalRun.test.tsx
> +      title: 'test',
title is no longer needed in the store, same with medications

2020-09-12 17:48 UTC, jackcmeyer commented on src/__tests__/labs/ViewLabs.test.tsx
> +    title: '',
title is no longer needed in the store

2020-09-12 17:48 UTC, jackcmeyer commented on src/page-header/title/useTitle.tsx
>  }
seems like we should be able to remove this so that we we only have two hooks `useTitle` and `useUpdateTitle`

2020-09-19 15:32 UTC, tehKapa reviewed
@blestab can you resolve conflicts in this file? src/__tests__/labs/Labs.test.tsx

2020-09-22 15:31 UTC, tehKapa reviewed
@blestab something goes wrong with build
```
./src/medications/search/ViewMedications.tsx
Cannot find file '../../page-header/title/useTitle' in './src/medications/search'.
```

2020-09-22 15:47 UTC, blestab commented
> 
> 
> @blestab something goes wrong with build
> 
> ```
> ./src/medications/search/ViewMedications.tsx
> Cannot find file '../../page-header/title/useTitle' in './src/medications/search'.
> ```

Hi taking a look, sorry for the delay with this. Must have sneaked back in during merge conflict resolution.

2020-09-22 17:38 UTC, blestab commented
@jackcmeyer i have cleaned up references to title from our tests.
@tehKapa our build should be all good now.

2020-09-23 02:20 UTC, merged