updated styles to match the add allergy button
HospitalRun/hospitalrun-frontend pull request #2446
Opened 2020-10-25 11:53 UTC by smsriharsha

Fixes #2441 Patient View: Buttons hover style inconsistency 

**Changes proposed in this pull request:**

1. changed the colors to match the add allergy button

I have run the test for the modified code and 
[test results.txt](https://github.com/HospitalRun/hospitalrun-frontend/files/5434648/test.results.txt).

Please review and let me know if i have made any mistake.

2020-10-25 12:52 UTC, blestab commented
Hi @smsriharsha 
Thank you for your contribution. May you go ahead and sign the CLA

2020-10-26 09:53 UTC, blestab requested changes
May you fix the lint errors:

`npm run lint:fix` and then commit the changes

2020-12-06 09:57 UTC, blestab approved these changes

2020-12-06 09:59 UTC, blestab commented
Hi @jackcmeyer i believe this one is all set. Merge and lint issues were resolved.

2020-12-09 04:02 UTC, jackcmeyer approved these changes

2020-12-09 04:02 UTC, merged