refactor(edit patient): use react-query when editing a patient
HospitalRun/hospitalrun-frontend pull request #2466
Opened 2020-10-31 20:08 UTC by giulianovarriale

Fixes #[replace brackets with the issue number that your pull request addresses].

**Changes proposed in this pull request:**

- [list out summary of changes here]
- [list out summary of changes here]
- [list out summary of changes here]
- [etc]

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

- [Link of the new dependency]
- [Link of the new dependency]
- [etc]

_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)_

2020-10-31 22:13 UTC, giulianovarriale commented
The PR is not finished yet, I opened it already for two reasons:
1. I'm participating in hacktoberfest and today is the last day to contribute.
Anyway, I'll finish my contribution because this is the right thing to do and also I'm having fun implementing react-query on the project.
2. I'm wondering what you expect to be tested in here, since the feature remains the same, but the implementation has been changed. For this PR, I was thinking to write a test for the validator and also a test for the hook, what do you think?

2020-11-01 23:15 UTC, jackcmeyer requested changes

2020-11-01 23:15 UTC, jackcmeyer commented on src/patients/util/validate-patient.ts
> +interface IValidationError {
Let's name this as `PatientValidationError`

2020-11-01 23:15 UTC, jackcmeyer commented on src/patients/util/validate-patient.ts
> +interface IValidationError {
It should also extend Error. See other validations on how to do this.

2020-11-01 23:15 UTC, jackcmeyer commented on src/patients/hooks/useUpdatePatient.tsx
> +export default function useUpdatePatient() {
upon success of the mutation, in should update the patient in the cache.

2020-11-01 23:15 UTC, jackcmeyer commented on src/patients/edit/EditPatient.tsx
> +        error={updateError ?? undefined}
I think we can simply do `updateError`

2020-11-01 23:15 UTC, jackcmeyer commented on src/patients/util/validate-patient.ts
> +    // Only add to error obj if there's an error
I think code is clear enough, we can remove these comments

2020-11-01 23:16 UTC, jackcmeyer commented
>  For this PR, I was thinking to write a test for the validator and also a test for the hook, what do you think?

I think this sounds perfect.

2020-11-02 08:42 UTC, giulianovarriale commented
@jackcmeyer TBH, I didn't write the validator code. I just copied and pasted from the patient-slice file. I think the validator should be out of the scope of this PR. What I'm gonna do is to open a new PR for the validator and once that one is merged we can rebase this one and use it in here. Do you agree?

2020-11-02 22:33 UTC, giulianovarriale commented
@jackcmeyer Please, before moving on with this PR, take a look on this one: https://github.com/HospitalRun/hospitalrun-frontend/pull/2471

2020-11-06 20:42 UTC, tehKapa submitted a review, later dismissed

2020-11-15 16:26 UTC, tehKapa commented
@giulianovarriale can you resolve the conflict? thanks

2020-11-19 08:35 UTC, giulianovarriale commented
I did that already on my local environment. I'm writing the hook test. Once I finished it, I'll push it.

2020-11-26 23:48 UTC, giulianovarriale commented
@tehKapa It is ready for review again.

2020-11-28 18:20 UTC, tehKapa approved these changes

2021-06-01 21:10 UTC, closed without merging