Create Patient History tab #2255
HospitalRun/hospitalrun-frontend pull request #2470
Opened 2020-11-01 15:30 UTC by VictorJuez

Fixes #2255 - Create Patient History tab

**Changes proposed in this pull request:**

- Created a patient history tab available in the patient profile.
- Show in chronological order the events (Labs and Appointments) that have happened to the patient
    - The information shown for Labs is the Lab Type
    - The information shown for Appointments is the Appointment Reason
- Added tests for all the code created

2020-11-03 00:50 UTC, jackcmeyer commented
@VictorJuez before we can review this, can  you please  fix the merge conflicts and make the pull requests checks pass. Thanks!

2020-12-09 22:40 UTC, blestab requested changes
I am unable to verify this functionality due to a typescript error:

```
TypeScript error in /workspace/hospitalrun-frontend/src/patients/history/HistoryTable.tsx(27,27):
Property 'id' does not exist on type 'PatientHistoryRecord'.  TS2339

    25 |   return (
    26 |     <Table
  > 27 |       getID={(row) => row.id}
       |                           ^
```

2020-12-09 22:40 UTC, blestab commented on src/__tests__/patients/history/HistoryTab.test.tsx
> +})
May you add a newline at the of the file

2020-12-09 22:40 UTC, blestab commented on src/patients/history/mappers/HistoryRecordsMapper.tsx
> +}
May you add a newline at the end of the file

2020-12-09 22:40 UTC, blestab commented on src/patients/history/HistoryTable.tsx
> +      getID={(row) => row.id}
This should be recordId not id?

2020-12-18 02:49 UTC, closed without merging