fix: fixed buttons alignment by giving right margin (#1)
HospitalRun/hospitalrun-frontend pull request #2519
Opened 2020-12-15 16:26 UTC by Adarsh710

Fix #2518 

**Changes proposed in this pull request:**

- Added class `mr-3` to all button groups
- Removed class `mr-2` from Resolve button in ViewIncidentDetails component for better alignment

**Total files changed** : 9

2020-12-15 17:00 UTC, blestab requested changes
Thank you @Adarsh710, looking good on the new forms as well as some edit forms.

May you also fix these edit forms: 
- Patient Edit
![image](https://user-images.githubusercontent.com/5468546/102246413-66fb5380-3f07-11eb-873b-1e7f1c7cc2c1.png)

- Appointment Edit
![image](https://user-images.githubusercontent.com/5468546/102246456-767a9c80-3f07-11eb-9049-005d3d773888.png)

2020-12-15 17:22 UTC, Adarsh710 commented
> Thank you @Adarsh710, looking good on the new forms as well as some edit forms.
> 
> May you also fix these edit forms:
> 
> * Patient Edit
>   ![image](https://user-images.githubusercontent.com/5468546/102246413-66fb5380-3f07-11eb-873b-1e7f1c7cc2c1.png)
> * Appointment Edit
>   ![image](https://user-images.githubusercontent.com/5468546/102246456-767a9c80-3f07-11eb-9049-005d3d773888.png)

Nice catch, fixing these too

2020-12-15 18:05 UTC, blestab approved these changes
LGTM

2021-01-30 20:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HospitalRun/hospitalrun-frontend?pullRequest=2519) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/HospitalRun/hospitalrun-frontend?pullRequest=2519) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Adarsh710<br/>:x: tehKapa<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HospitalRun/hospitalrun-frontend?pullRequest=2519) it.</sub>

2021-02-28 18:01 UTC, merged