fix:added mobile validation for 11 digits and on error scroll to top
HospitalRun/hospitalrun-frontend pull request #2678
Opened 2021-05-14 18:34 UTC by jayavardhan3112

Fixes #2675

Changes proposed in this pull request:

added mobile validation for 11 digits
scrolling to the top when there is an error while creating / updating the patient
since its misleading and user might not be aware if the error is in the button or its a validation check

2021-05-14 18:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HospitalRun/hospitalrun-frontend?pullRequest=2678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/HospitalRun/hospitalrun-frontend?pullRequest=2678) before we can accept your contribution.<br/><hr/>**Reverie-PC** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HospitalRun/hospitalrun-frontend?pullRequest=2678) it.</sub>

2021-05-18 11:10 UTC, tehKapa commented
Hi @jayavardhan3112, can you sign our Contributor License Agreement? Thanks

2021-05-18 12:01 UTC, jayavardhan3112 commented
> Hi @jayavardhan3112, can you sign our Contributor License Agreement? Thanks

I have already done that, but dont know why its not updating

2021-05-21 04:30 UTC, DrewGregory commented
> > Hi @jayavardhan3112, can you sign our Contributor License Agreement? Thanks
> 
> I have already done that, but dont know why its not updating

I believe the reason is that the author email on your commits doesn't correspond to your GitHub email. I would recommend amending your commits so that your email corresponds to your GitHub account: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

2021-05-21 22:49 UTC, anthonyaperez requested changes
Nice work! Please make sure to address the changes mentioned, including the style errors that the linter throws (you can either try `npm run lint:fix` or fix them manually).

2021-05-21 22:49 UTC, anthonyaperez commented on src/patients/util/validate-patient.ts
> +  (!validator.isMobilePhone(phone.value) || !new RegExp(`^[\\s\\d]{${10}}$`).test(phone.value)) ? 'patient.errors.invalidPhoneNumber' : undefined,
Declaring a new object within a ternary operator makes it a bit hard to read...maybe we can do something like this:
```
const validPhoneRegex = /^[\\s\\d]{${10}}$/

const validatePhoneNumbers = (phoneNumbers: ContactInfoPiece[] | undefined) =>
  (phoneNumbers ?? []).map((phone) =>  
    (!validator.isMobilePhone(phone.value) || !validPhoneRegex.test(phone.value)) ? 'patient.errors.invalidPhoneNumber' : undefined,  
)
```

Another option you have is to create a static utility method to do the regex checking, but that isn't necessary here.

2021-09-03 00:13 UTC, closed without merging